language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: rf.nonato@gmail.com
    on_success: rf.nonato@gmail.com
